class Game(val name: String, val board: Board, val enemyBoard: Board)

@startuml
hide empty members

class Board{
+moves: List<Move>
+turn
}
class Move{
+player
+shot
+status
}

class Game{
{static} +board:Board
{static} +name
{static} +enemyBoard:Board
}

class Cell{

}

class Ship{
+type: ShipType
-pos: Position

}

Ship <|-- Cell

'https://plantuml.com/class-diagram
@enduml